// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914175427_AddAirportFees")]
    partial class AddAirportFees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<double>("DepartureFee")
                        .HasColumnType("double precision");

                    b.Property<double>("LandingFeePer1000Lb")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Los Angeles",
                            Code = "LAX",
                            DepartureFee = 1200.0,
                            LandingFeePer1000Lb = 7.5,
                            Latitude = 33.942501,
                            Longitude = -118.40799699999999,
                            Name = "Los Angeles International Airport"
                        },
                        new
                        {
                            Id = 2,
                            City = "New York",
                            Code = "JFK",
                            DepartureFee = 1600.0,
                            LandingFeePer1000Lb = 9.5,
                            Latitude = 40.639446999999997,
                            Longitude = -73.779317000000006,
                            Name = "John F. Kennedy International Airport"
                        },
                        new
                        {
                            Id = 3,
                            City = "Chicago",
                            Code = "ORD",
                            DepartureFee = 1100.0,
                            LandingFeePer1000Lb = 7.25,
                            Latitude = 41.9786,
                            Longitude = -87.904799999999994,
                            Name = "Chicago O'Hare International Airport"
                        },
                        new
                        {
                            Id = 4,
                            City = "Dallas",
                            Code = "DFW",
                            DepartureFee = 900.0,
                            LandingFeePer1000Lb = 5.5,
                            Latitude = 32.896801000000004,
                            Longitude = -97.038002000000006,
                            Name = "Dallas Fort Worth International Airport"
                        },
                        new
                        {
                            Id = 5,
                            City = "Atlanta",
                            Code = "ATL",
                            DepartureFee = 850.0,
                            LandingFeePer1000Lb = 4.75,
                            Latitude = 33.636699999999998,
                            Longitude = -84.428100999999998,
                            Name = "Hartsfield-Jackson Atlanta International Airport"
                        },
                        new
                        {
                            Id = 6,
                            City = "San Francisco",
                            Code = "SFO",
                            DepartureFee = 1400.0,
                            LandingFeePer1000Lb = 8.25,
                            Latitude = 37.619805999999997,
                            Longitude = -122.374821,
                            Name = "San Francisco International Airport"
                        },
                        new
                        {
                            Id = 7,
                            City = "Seattle",
                            Code = "SEA",
                            DepartureFee = 950.0,
                            LandingFeePer1000Lb = 6.0,
                            Latitude = 47.449001000000003,
                            Longitude = -122.308998,
                            Name = "Seattle-Tacoma International Airport"
                        },
                        new
                        {
                            Id = 8,
                            City = "Miami",
                            Code = "MIA",
                            DepartureFee = 1000.0,
                            LandingFeePer1000Lb = 6.25,
                            Latitude = 25.793199999999999,
                            Longitude = -80.290604000000002,
                            Name = "Miami International Airport"
                        },
                        new
                        {
                            Id = 9,
                            City = "Boston",
                            Code = "BOS",
                            DepartureFee = 1300.0,
                            LandingFeePer1000Lb = 8.0,
                            Latitude = 42.3643,
                            Longitude = -71.005202999999995,
                            Name = "Boston Logan International Airport"
                        },
                        new
                        {
                            Id = 10,
                            City = "Denver",
                            Code = "DEN",
                            DepartureFee = 900.0,
                            LandingFeePer1000Lb = 5.25,
                            Latitude = 39.861697999999997,
                            Longitude = -104.672997,
                            Name = "Denver International Airport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
